{
 "title": "ENEDIS",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Valeurs pour les 3 derniers jours",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  metric AS metric,\n  conso_watt\n\nFROM enedis_metrics\nWHERE\n  $__timeFilter(time)\nORDER BY time\n"
    }
   ]
  },
  { "title": "Prix moyen du kWh en France", "type": "stat", "gridPos": { "h": 3, "w": 5, "x": 0, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "Puissance souscrite", "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 5, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "Puissance du raccordement", "type": "stat", "gridPos": { "h": 3, "w": 4, "x": 9, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Recherche de valeurs",
   "type": "table",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  metric AS metric,\n  conso_watt\n\nFROM enedis_metrics\nORDER BY time desc\n"
    }
   ]
  },
  {
   "title": "Conso moyenne (semaine)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT week(time) as NUM_SEMAINE, avg(conso_watt)as Moyenne FROM enedis_metrics group by NUM_SEMAINE order by NUM_SEMAINE desc"
    }
   ]
  },
  {
   "title": "Conso Max (semaine)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT week(time) as NUM_SEMAINE, max(conso_watt) as Maximum FROM enedis_metrics group by NUM_SEMAINE order by NUM_SEMAINE desc"
    }
   ]
  },
  {
   "title": "Conso Min (semaine)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT week(time) as NUM_SEMAINE, min(conso_watt) as Minimum FROM enedis_metrics group by NUM_SEMAINE order by NUM_SEMAINE desc"
    }
   ]
  },
  {
   "title": "Valeurs pour la journée d'hier",
   "type": "graph",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  metric AS metric,\n  conso_watt\n\nFROM enedis_metrics\nWHERE\n  $__timeFilter(time)\nORDER BY time\n"
    }
   ]
  }
 ]
}