version: "3"
services:
  scrypto:
    image: baldurr/pynedis:latest
    container_name: pynedis
    environment:
      - EXEC_HOUR=02:30:00
      - COLLECT_ID=11111111111111111111
      - API_TOKEN=hbbiubuuhuuuu
      - SQL_USER=root4
      - SQL_PASSWORD=root4
      - SQL_HOST=192.168.1.20
      - SQL_DB=db_enedis
      - SQL_PORT=3307
      
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"

    restart: unless-stopped
